Community and Networks sections
frequency-chain/docs pull request #67
Opened 2024-03-01 14:37 UTC by wilwade

New Sections:
- Community
- Networks
  - Running a Node
  - Running a Collator
  - Decentralization
  - Troubleshooting

Updated some markdown inconsistencies

2024-03-09 02:31 UTC, wesbiggs requested changes
Finished review.

2024-03-09 02:31 UTC, wesbiggs commented on pages/Networks/Collator.md
> +1. Remember that the Collator Node MUST be able to peer with others, but access to HTTP and WebSocket RPCs MUST be restricted.
Unsure what is meant by "MUST be restricted". In what way, and by what mechanism? The suggested flags include `--rpc-external` which I would (probably wrongly) assume means unrestricted?

2024-03-09 02:31 UTC, wesbiggs commented on pages/Networks/Collator.md
> +   - Flags applied after a `--` are applied to built in Relay Chain node.
Suggest: Drop the first "applied"; add "the" before "built in".

2024-03-09 02:31 UTC, wesbiggs commented on pages/Networks/Collator.md
> +1. Generate a new Controller Account aura key: `subkey generate`
Capitalize Aura Key in line with Session Key below?

2024-03-09 02:31 UTC, wesbiggs commented on pages/Networks/Collator.md
> +   - While it is possible for your session key to match your Controller Account, but not recommended.
Drop "While" or add "it is" before "not recommended".

2024-03-09 02:31 UTC, wesbiggs commented on pages/Networks/Collator.md
> +1. Wait until the Relay Chain and parachain are up to date and synced.
How is this observed?

2024-03-09 02:31 UTC, wesbiggs commented on pages/Networks/Collator.md
> +See [Decentralization](./Decentralization.md) for more details on how to currently become an active Collator Node.
I would boldly go with:
"... for **current** details on how to become ..."

2024-03-09 02:31 UTC, wesbiggs commented on pages/Networks/Collator.md
> +See [Troubleshooting](./Troubleshooting.md) for help when things go wrong.
"if", perhaps?

2024-03-09 02:31 UTC, wesbiggs commented on pages/Networks/Decentralization.md
> +These collators are not removed for lack of block production and do not require a stake or bond to operate.
Capitalize Collators

2024-03-09 02:31 UTC, wesbiggs commented on pages/Networks/Decentralization.md
> +To accomplish this, there are has three key phases:
typo, remove "has"

2024-03-09 02:31 UTC, wesbiggs commented on pages/Networks/Decentralization.md
> +- Progression highly depends on the safety and security of the network.
Progression "to this phase"?

2024-03-09 02:31 UTC, wesbiggs commented on pages/Networks/Decentralization.md
> +- Collators will form the foundation of the public Collator set.
Perhaps "Accepted applicants will form..."

2024-03-09 02:31 UTC, wesbiggs commented on pages/Networks/Decentralization.md
> +- Organizations guarantee public transparency and access to all non-malicious transactions to the block.
Unclear to me what is meant by the second part here. Maybe just the phrasing?

2024-03-09 02:31 UTC, wesbiggs commented on pages/Networks/Decentralization.md
> +3. Public Collators: Anyone can register as a Collator candidate.
Perhaps just "Open Registration"?

2024-03-09 02:31 UTC, wesbiggs commented on pages/Networks/Node.md
> +| Frequency |  `frequency.[arch]` |
Should we use Mainnet and Testnet here (and in next section)?

2024-03-09 02:31 UTC, wesbiggs commented on pages/Networks/Node.md
> +The Frequency node has a built in relay chain node to support checking block validation.
Style guide has "Frequency Node" capitalized (used on this line and the next)

Should we capitalize "Relay Chain"? (Not specified in style guide) (this line and the next)

2024-03-09 02:31 UTC, wesbiggs commented on pages/Networks/Node.md
> +Running a node that will have a high volume from one or more servers requires altering the defaults.
high volume of what?

2024-03-09 02:31 UTC, wesbiggs commented on pages/Networks/Node.md
> +If you are running an RPC node there are several options to be aware of.
Possibly "RPC Node" capitalized?

2024-03-09 02:31 UTC, wesbiggs commented on pages/Networks/Node.md
> +`frequency-binary <parachain-args> -- <relay-chain-args>`
Is `frequency-binary` a stand-in for `./frequency`, or are these different executables? If the former, can we standardize on one?

2024-03-09 02:31 UTC, wesbiggs commented on pages/Networks/Node.md
> +Used for local development on or against Frequency.
suggest dropping "on or against Frequency", to me it raises more questions than it answers (Frequency the code? Frequency the network?)

2024-03-11 14:37 UTC, wilwade commented on pages/Community.md
> +- [Twitter: @one_frequency](https://twitter.com/one_frequency)
I can do `𝕏`, but I'll leave the url as `twitter.com` is still canonical per the redirects.

2024-03-11 14:41 UTC, wilwade commented on pages/Networks/Collator.md
> +   - When an invulnerable Collator, should be set as one of the "invulnerable keys"
Updated to:
`- For an invulnerable Collator, this is the key that must be set by governance as "invulnerable".`

2024-03-11 14:42 UTC, wilwade commented on pages/Networks/Collator.md
> +1. Remember that the Collator Node MUST be able to peer with others, but access to HTTP and WebSocket RPCs MUST be restricted.
`- Flags applied after a `--` are for the internal Relay Chain node.`

2024-03-11 14:43 UTC, wilwade commented on pages/Networks/Collator.md
> +   - Flags applied after a `--` are applied to built in Relay Chain node.
`- Flags applied after a `--` are for the internal Relay Chain node.`

2024-03-11 14:45 UTC, wilwade commented on pages/Networks/Collator.md
> +   - While it is possible for your session key to match your Controller Account, but not recommended.
Just updated to a stronger `Controller Keys should _not_ be used as Session Keys.`

2024-03-11 14:47 UTC, wilwade commented on pages/Networks/Collator.md
> +1. Wait until the Relay Chain and parachain are up to date and synced.
The logs show it, but you can also call RPCs to find it. Not sure if I want to detail any of that here. A bit of, if you cannot figure out how to check that, then I am missing a lot of details on the other steps?

2024-03-11 14:47 UTC, wilwade commented on pages/Networks/Collator.md
> +   - Collator: Can be auto-generated
The idea was to make it clear that collators can auto-generate, but there are reasons others (bootnodes in particular) cannot be.

Replaced with `- Can be auto-generated for most non-bootnodes.`

2024-03-11 14:51 UTC, wilwade commented on pages/Networks/Decentralization.md
> +- Organizations guarantee public transparency and access to all non-malicious transactions to the block.
Reworded:

`- Organizations guarantee public transparency and will add all non-malicious transactions to the block.`

2024-03-11 14:53 UTC, wilwade commented on pages/Networks/Node.md
> +Running a node that will have a high volume from one or more servers requires altering the defaults.
... of transactions...

2024-03-11 14:55 UTC, wilwade commented on pages/Networks/Node.md
> +If you are running an RPC node there are several options to be aware of.
I don't think so? If we do that we would want to capitalize Archive Node as well. Likely we shouldn't capitalize Node for Collator Node either, but that is a larger change

2024-03-11 14:56 UTC, wilwade commented on pages/Networks/Node.md
> +`frequency-binary <parachain-args> -- <relay-chain-args>`
It is a stand-in, but I'll standardize on `frequency`

2024-03-11 14:58 UTC, wilwade commented on pages/Networks/Node.md
> +The list of possible targets is long, but some common ones are listed under [Node Troubleshooting](./Troubleshooting.md).
There isn't a way current :( You have to read the code.

Updated to:

```
The list of possible targets is long and requires reading the code of the specific library you are targeting, but some common ones are listed under [Node Troubleshooting](./Troubleshooting.md).
```

2024-03-11 15:00 UTC, wilwade commented on pages/Networks/Troubleshooting.md
> +Thus, for basic short-term fixes, even public nodes may be a fix.
Updated to "Thus, use of a public node may be short-term fix for some situations."

2024-03-11 19:53 UTC, wesbiggs commented on pages/Networks/Troubleshooting.md
> +Thus, for basic short-term fixes, even public nodes may be a fix.
nit (or typo): "may be *a* short-term fix"

2024-03-11 19:56 UTC, wesbiggs commented on pages/Networks/Collator.md
> +1. Wait until the Relay Chain and parachain are up to date and synced.
OK

2024-03-11 19:59 UTC, wesbiggs commented on pages/Networks/Collator.md
> +See [Decentralization](./Decentralization.md) for current details on how to currently become an active Collator Node.
Now it has too much currency, remove "currently"?

2024-03-12 12:34 UTC, wilwade commented on pages/Networks/Node.md
> +| Frequency |  `frequency.[arch]` |
Good idea. Updated some.

2024-03-12 12:34 UTC, wilwade commented on pages/Networks/Node.md
> +The Frequency node has a built in relay chain node to support checking block validation.
I thought I said this elsewhere, but I do not think we should.

2024-03-12 14:30 UTC, enddynayn commented on pages/Networks/Node.md
> +Archive nodes are useful for accessing historical states, but Frequency is designed to make that need rare.
what do you mean by Frequency is designed to make that need rare?

2024-03-12 14:35 UTC, wilwade commented on pages/Networks/Node.md
> +Archive nodes are useful for accessing historical states, but Frequency is designed to make that need rare.
I don't think so? At least not on this page. We talked about having it in some of the whitepaper-y sections, but until we are actively working on pruning, it isn't needed.

2024-03-12 14:37 UTC, enddynayn commented on pages/Networks/index.md
> +{{#button-links}}
<img width="696" alt="Screenshot 2024-03-12 at 7 36 42 AM" src="https://github.com/LibertyDSNP/frequency-docs/assets/3433442/150f5d62-aa2b-431b-9ac6-515069f70ac3">

2024-03-12 14:40 UTC, enddynayn commented on pages/Networks/Collator.md
> +   - Example:
Nice to see examples. They are always helpful.

2024-03-12 14:42 UTC, enddynayn commented on pages/Networks/Node.md
> +Archive nodes are useful for accessing historical states, but Frequency is designed to make that need rare.
Should we remove that statement?

2024-03-12 14:42 UTC, enddynayn approved these changes
👍 Nice to see the Network section.

2024-03-12 14:43 UTC, wilwade commented on pages/Networks/index.md
> +{{#button-links}}
That's a plugin for mdBook. So it doesn't render in markdown (however your note made me look and fix an issue with table margin bottom):

<img width="1101" alt="image" src="https://github.com/LibertyDSNP/frequency-docs/assets/1252199/8acd7687-b1da-4299-8185-107986da5bdb">

2024-03-12 16:53 UTC, jeanettedepatie commented on pages/Networks/Collator.md
periods are not used consistently throughout for end of line.  I see a pattern but some of them don't match.

2024-03-12 17:00 UTC, jeanettedepatie commented on pages/Networks/Collator.md
Also I think we should avoid exclamation marks.

2024-03-12 17:08 UTC, jeanettedepatie commented on pages/Networks/Decentralization.md
> +- Collators are selected based on bond, governance support, and uptime that will be developed.
I find this sentence confusing.  Developed by whom?

2024-03-12 17:21 UTC, jeanettedepatie commented on pages/Networks/Node.md
> +Each node also has a Relay Chain node as well and these options will often apply with different defaults to the Relay Chain.
Remove either "also" or "as well" seems redundant.

2024-03-12 17:22 UTC, jeanettedepatie commented on pages/Networks/Node.md
> +
Relay Chain should be capitalized throughout.

2024-03-13 12:59 UTC, wilwade commented on pages/Networks/Decentralization.md
> +- Collators are selected based on bond, governance support, and uptime that will be developed.
Updated, but cannot give a who, just a when.

```suggestion
- Collators are selected based on bond, governance support, and uptime that will be developed in the future.
```

2024-03-13 13:15 UTC, wilwade commented on pages/Networks/Collator.md
Tried to get the periods on lists standardized. Data point doesn't have it, others do. See if that works.

I updated the security callout that used the exclamation mark to a UI element:
![image](https://github.com/LibertyDSNP/frequency-docs/assets/1252199/768328ba-291c-4a85-8c74-0caf4638c901)

2024-03-19 15:27 UTC, wesbiggs approved these changes
Good stuff. One comment on formatting nit, but approving anyway.

2024-03-19 15:27 UTC, wesbiggs commented on pages/Networks/Collator.md
> +    - 4 physical cores @ 3.4GHz.
Minor nits: the trailing period here is inconsistent with this section; however, the Key Types section uses trailing periods for similar phrases that are not complete sentences. (I personally favor not having periods for list items that are not complete sentences, but fine either way.)

2024-03-20 13:28 UTC, wilwade commented on pages/Networks/Node.md
> +Archive nodes are useful for accessing historical states, but Frequency is designed to make that need rare.
Yeah, I think I will.

2024-03-20 13:33 UTC, wilwade commented on pages/Networks/Collator.md
> +    - 4 physical cores @ 3.4GHz.
I tried to keep it to only full sentences, or ones that combined with the header are full (aka some of the ones in the key types section). This one in particular shouldn't be there and I cleaned up the ones in the key section more as well.

2024-06-26 18:09 UTC, shannonwells approved these changes
My comments are suggested improvements, and therefore non-blocking.

2024-06-26 18:09 UTC, shannonwells commented on pages/Networks/Node.md
> +These are NOT the only options (see `--help`), but are the important ones.
```suggestion
The options described below are the most important.  For more, see `--help`.
```

2024-06-26 18:09 UTC, shannonwells commented on pages/Networks/Node.md
> +- [Substrate Docs: Deployment](https://docs.substrate.io/deploy/) - Great starter place to understand node deployments
```suggestion
- [Substrate Docs: Deployment](https://docs.substrate.io/deploy/) - A starting place to understand node deployments
```

2024-06-26 18:09 UTC, shannonwells commented on pages/Networks/Node.md
> +Running a node that will have a high volume of transactions or queries from one or more servers requires altering the defaults.
I think it would be useful to give some parameters for what you mean by "high volume" instead of or in addition to saying "high volume"

2024-06-26 18:09 UTC, shannonwells commented on pages/Networks/Node.md
> +Logging is `--log <LOG_PATTERN>...` which is `<target>=<level>` for example: `-lsync=debug`.
```suggestion
For logging, use `--log <target>=<level>`.  For example: `-lsync=debug`.
```

2024-06-26 18:09 UTC, shannonwells commented on pages/Networks/Node.md
> +Used for local development.
... only?

2024-06-26 18:09 UTC, shannonwells commented on pages/Networks/Node.md
> +If on macOS, you currently need to add `--platform=linux/amd64`
```suggestion
If on macOS, add `--platform=linux/amd64`
```

2024-06-26 18:33 UTC, wilwade commented on pages/Networks/Node.md
> +Running a node that will have a high volume of transactions or queries from one or more servers requires altering the defaults.
It depends on so many things, I'm not sure how to quantify it. Open to ideas.

2024-09-06 20:08 UTC, enddynayn commented on pages/Networks/Decentralization.md
> +# Collator Decentralization Roadmap
Nice!

2024-09-06 20:12 UTC, enddynayn commented on pages/Architecture/OperationalModel.md
> +A separate system for testing and development known as Testnet uses validators on the Paseo Relay Chain.
This might be a good place to link to PolkadotJS app.

2024-10-24 21:33 UTC, closed without merging